const custData = [
  {
    Customer_ID: 1,
    Area: 2,
    SubArea: 7,
    CompanyName: "Chatterbridge",
    Address: "Apt 298",
    ContactName: "Suite 93",
    PinNo: 700061,
    MobileNo: 9138265163,
    phNo: "9202185078",
    Grade: 1,
    QuotedPrice: 691683.13,
    WantedPrice: 608071.94,
    Status: 5.14,
    ReferenceName: "Aili Lambswood",
    EmailId: "carno0@google.cn",
    Remarks:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    AboutHoliday:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    Vendor: "Cchaddie Sorton",
    SecondVendor: "Caroljean Arno",
    AreaDetail: [{}, {}, {}],
    ActionDate: "31/07/2024",
  },
  {
    Customer_ID:2,
    Area: 9,
    SubArea: 1,
    CompanyName: "Skinix",
    Address: "17th Floor",
    ContactName: "Room 1596",
    PinNo: 700060,
    MobileNo: 9396049151,
    phNo: "8904376392",
    Grade: 1,
    QuotedPrice: 612264.7,
    WantedPrice: 525970.49,
    Status: 3.7,
    ReferenceName: "Guillemette Stansbury",
    EmailId: "bcliburn1@furl.net",
    Remarks:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    AboutHoliday:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    Vendor: "Marshal Thraves",
    SecondVendor: "Bibby Cliburn",
    AreaDetail: [{}, {}, {}],
    ActionDate: "06/05/2024",
  },
  {
    Customer_ID:3,
    Area: 2,
    SubArea: 1,
    CompanyName: "Photobug",
    Address: "PO Box 14440",
    ContactName: "Apt 891",
    PinNo: 700060,
    MobileNo: 9704953454,
    phNo: "1791619202",
    Grade: 3,
    QuotedPrice: 598409.25,
    WantedPrice: 579107.55,
    Status: 1.74,
    ReferenceName: "Janna Rosenberg",
    EmailId: "balten2@drupal.org",
    Remarks:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    AboutHoliday:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    Vendor: "Debbi Maplethorp",
    SecondVendor: "Baldwin Alten",
    AreaDetail: [{}, {}, {}, {}, {}],
    ActionDate: "24/12/2023",
  },
  {
    Customer_ID:4,
    Area: 2,
    SubArea: 8,
    CompanyName: "Skyvu",
    Address: "PO Box 50936",
    ContactName: "Suite 55",
    PinNo: 700063,
    MobileNo: 9220569151,
    phNo: "8145708930",
    Grade: 2,
    QuotedPrice: 507968.68,
    WantedPrice: 626675.17,
    Status: 5.49,
    ReferenceName: "Joana Thumim",
    EmailId: "jgiblett3@tmall.com",
    Remarks:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    AboutHoliday:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    Vendor: "Quincy Kastel",
    SecondVendor: "Joby Giblett",
    AreaDetail: [{}, {}, {}, {}],
    ActionDate: "29/09/2023",
  },
  {
    Customer_ID:5,
    Area: 7,
    SubArea: 5,
    CompanyName: "Browsedrive",
    Address: "11th Floor",
    ContactName: "Suite 73",
    PinNo: 700060,
    MobileNo: 9182325424,
    phNo: "4401830910",
    Grade: 1,
    QuotedPrice: 696263.94,
    WantedPrice: 602759.16,
    Status: 2.61,
    ReferenceName: "Reece Trencher",
    EmailId: "bletterick4@umn.edu",
    Remarks:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    AboutHoliday:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    Vendor: "Lance Davydkov",
    SecondVendor: "Betsy Letterick",
    AreaDetail: [{}, {}, {}, {}, {}],
    ActionDate: "25/02/2024",
  },
  {
    Customer_ID: 6,
    Area: 3,
    SubArea: 1,
    CompanyName: "Brainbox",
    Address: "Suite 53",
    ContactName: "Suite 88",
    PinNo: 700069,
    MobileNo: 9570907691,
    phNo: "4004216117",
    Grade: 1,
    QuotedPrice: 596436.16,
    WantedPrice: 696443.84,
    Status: 1.96,
    ReferenceName: "Andris Bunner",
    EmailId: "thordle5@amazon.co.uk",
    Remarks:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    AboutHoliday:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    Vendor: "Guglielmo Densie",
    SecondVendor: "Tally Hordle",
    AreaDetail: [{}, {}, {}, {}],
    ActionDate: "19/07/2024",
  },
  {
    Customer_ID: 7,
    Area: 3,
    SubArea: 7,
    CompanyName: "Flashspan",
    Address: "Suite 72",
    ContactName: "PO Box 31700",
    PinNo: 700062,
    MobileNo: 9790345614,
    phNo: "4497033502",
    Grade: 3,
    QuotedPrice: 607002.91,
    WantedPrice: 690167.27,
    Status: 3.72,
    ReferenceName: "Ginger Ashman",
    EmailId: "cmattia6@china.com.cn",
    Remarks:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    AboutHoliday:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
    Vendor: "Osgood Hotchkin",
    SecondVendor: "Chrystel Mattia",
    AreaDetail: [{}, {}, {}],
    ActionDate: "02/10/2023",
  },
  {
    Customer_ID: 8,
    Area: 6,
    SubArea: 6,
    CompanyName: "Abatz",
    Address: "9th Floor",
    ContactName: "PO Box 82978",
    PinNo: 700061,
    MobileNo: 9473195097,
    phNo: "5336164359",
    Grade: 2,
    QuotedPrice: 574439.58,
    WantedPrice: 554643.2,
    Status: 4.1,
    ReferenceName: "Dewie Lewsie",
    EmailId: "trosenblum7@whitehouse.gov",
    Remarks:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    AboutHoliday:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    Vendor: "Elden Andres",
    SecondVendor: "Taylor Rosenblum",
    AreaDetail: [{}, {}, {}, {}, {}],
    ActionDate: "26/08/2024",
  },
  {
    Customer_ID: 9,
    Area: 2,
    SubArea: 7,
    CompanyName: "Youtags",
    Address: "PO Box 14378",
    ContactName: "Room 722",
    PinNo: 700065,
    MobileNo: 9347321875,
    phNo: "4085114918",
    Grade: 3,
    QuotedPrice: 674808.0,
    WantedPrice: 598074.62,
    Status: 2.27,
    ReferenceName: "Shannah Pollard",
    EmailId: "rdeverale8@latimes.com",
    Remarks:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    AboutHoliday:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    Vendor: "Lynsey Da Costa",
    SecondVendor: "Raymund Deverale",
    AreaDetail: [{}, {}, {}],
    ActionDate: "16/11/2023",
  },
  {
    Customer_ID:10,
    Area: 3,
    SubArea: 7,
    CompanyName: "Trudoo",
    Address: "Suite 34",
    ContactName: "Apt 1063",
    PinNo: 700068,
    MobileNo: 9968278365,
    phNo: "4432797025",
    Grade: 2,
    QuotedPrice: 600644.24,
    WantedPrice: 567758.3,
    Status: 5.44,
    ReferenceName: "Carmina Pattemore",
    EmailId: "fhoys9@google.com.hk",
    Remarks:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    AboutHoliday:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    Vendor: "Lynea Smalles",
    SecondVendor: "Findlay Hoys",
    AreaDetail: [{}, {}, {}, {}],
    ActionDate: "19/12/2023",
  },
];
export default custData;
